# Generated by Django 5.1.4 on 2025-01-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tournament_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
